config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'forums#index'

  resources :forums do
    resources :topics do 
      resources :comments
    end        
  end

  post 'likes/:resource_name/:resource_id' => 'likes#create', :as => 'like'
  delete 'likes/:resource_name/:resource_id' => 'likes#destroy', :as => 'unlike'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :topic
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :topics
end

app/models/like.rb
class Like < ActiveRecord::Base
	def self.get_like_count(likeable_type,likeable_id)
      self.where(likeable_id:likeable_id,likeable_type:likeable_type).count
	end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	
	extend FriendlyId

	belongs_to :forum
	has_many :comments

	friendly_id :subject, use: [:slugged, :history]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  respond_to :html, :js

  def new
    @topic = Topic.friendly.find(params[:topic_id])
    @comment = @topic.comments.build  
    respond_with(@comment)
  end

  def edit
    @topic = Topic.friendly.find(params[:topic_id])
  end

  def create
    topic = Topic.friendly.find(params[:topic_id])
    @comment = topic.comments.build(comment_params.merge(user_id: current_user.id))    
    @comment.save
    respond_with(topic.forum,topic)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    topic = Topic.friendly.find(params[:topic_id])
    respond_with([topic.forum, topic])
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @forums = Forum.all
    respond_with(@forums)
  end

  def show
    respond_with(@forum)
  end

  def new
    @forum = Forum.new
    respond_with(@forum)
  end

  def edit
  end

  def create
    @forum = Forum.new(forum_params)
    @forum.save
    respond_with(@forum)
  end

  def update
    @forum.update(forum_params)
    respond_with(@forum)
  end

  def destroy
    @forum.destroy
    respond_with(@forum)
  end

  private
    def set_forum
      @forum = Forum.find(params[:id])
    end

    def forum_params
      params.require(:forum).permit(:title)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
   Like.create(:likeable_type=>params[:resource_name], :likeable_id=>params[:resource_id],:user_id=>current_user.id)    
    redirect_to :back, :notice => "success!!!"
  end

  def destroy
    target = Like.where(:likeable_type=>params[:resource_name], :likeable_id=>params[:resource_id],:user_id=>current_user.id).first
    if target
      target.destroy
    end
    redirect_to :back, :notice => "success!!!"

  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @forum = Forum.find(params[:forum_id])
    @topics = @forum.topics
    respond_with(@topics)
  end

  def show
    @comments = @topic.comments
    respond_with(@topic)
  end

  def new
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.new
    respond_with(@topic)
  end

  def edit
  end

  def create
    forum = Forum.find( params[:forum_id])
    topic = forum.topics.build(topic_params)
    topic.save
    respond_with(:forum, :topics)
  end

  def update
    @topic.update(topic_params)
    respond_with(@topic)
  end

  def destroy
    @topic.destroy
    respond_with(@topic)
  end

  private
    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:subject)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<tr id='comment_<%=@comment.id%>'>
<td><%=@comment.body%>
Like Count: [<%= Like.get_like_count(@comment.class,@comment.id) %>]
      <%= link_to "like it!!", like_path(:resource_name => @comment.class,
                                         :resource_id   => @comment.id),
                                         :method => :post %>
     <%= link_to "unlike it!!", unlike_path(
                                        :resource_name => @comment.class,
                                        :resource_id   => @comment.id),
                                        :method => :delete %>

</td>

<td>
<%=link_to 'Delete',forum_topic_comment_path(@comment.topic.forum, @comment.topic,@comment),{method: :delete} %></td>
<td>
<%= social_share_button_tag(@comment.body, :url => (forum_topic_comment_path(@comment.topic.forum, @comment.topic,@comment) +'#comment_'+@comment.id.to_s )) %></td>
</tr>

app/views/comments/_form.html.erb
<%= form_for [@topic.forum,@topic,@comment],{remote: true} do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comment_form").empty();
$('#comments_list').append("<%=escape_javascript(render 'comment' )%>");

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_topics_path(@topic.forum) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/comments/new.js.erb
$('#comment_form').html("<%=escape_javascript(render 'form' )%>");

app/views/forums/_form.html.erb
  <%= form_for(@forum) do |f| %>

  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>
      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<p> <%= link_to 'Forums Index', forums_path %> </p>
<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<p><%= link_to 'New Forum', new_forum_path %></p>

<h1>Listing forums</h1>


<% @forums.each do |forum| %>
  <li>
    <%= link_to forum.title, forum %>

    <p>      
      Like Count: [<%= Like.get_like_count(forum.class,forum.id) %>]
      <%= link_to "like it!!", like_path(:resource_name => forum.class,
                                         :resource_id   => forum.id),
                                         :method => :post %>
     <%= link_to "unlike it!!", unlike_path(
                                        :resource_name => forum.class,
                                        :resource_id   => forum.id),
                                        :method => :delete %>
    </p>
    <%if current_user.is_admin %> |
      <%= link_to 'Edit', edit_forum_path(forum) %> 
      <%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' } %> 
      
    <%end%>
  </li>
<% end %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p> <%= link_to 'Forums Index', forums_path %> </p>
<h1> Listing of <%= @forum.title %> Topics </h1>
<p><%= link_to 'Create Topic', new_forum_topic_path(@forum) %></p>
<div>
  <% @forum.topics.each do |topic| %>
  <li>
  <%= link_to topic.subject, [@forum, topic]%>
  <%= social_share_button_tag(topic.subject, :url => forum_topic_url(@forum, topic )) %></td>
  </li>
  <%end%>
</div>

<div>
	<%if current_user.is_admin %>
		<%= link_to 'Edit', edit_forum_path(@forum) %> |
	<% end %>
	<%= link_to 'Back', forums_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum Assignment</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %> 
</head>
<body>
<header>
	<% if user_signed_in? %>
	  <li>Welcome <%=current_user.email%></li>
	  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
	<% else %>
	  <li><%= link_to 'Sign in', new_user_session_path %></li>
	  <li><%= link_to 'Sign up', new_user_registration_path %></li>
	<% end %>
</header>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div> 


  <div class="field actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td> <%= topic.subject %>
      Like Count: [<%= Like.get_like_count(topic.class,topic.id) %>]
      <%= link_to "like it!!", like_path(:resource_name => topic.class,
                                         :resource_id   => topic.id),
                                         :method => :post %>
     <%= link_to "unlike it!!", unlike_path(
                                        :resource_name => topic.class,
                                        :resource_id   => topic.id),
                                        :method => :delete %>
    </td>
        <td><%= link_to 'Show', [@forum, topic] %></td>
        <td><%= social_share_button_tag(topic.subject, :url => forum_topic_url(topic.forum, topic )) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

app/views/topics/show.html.erb
<p><%= link_to 'Add Comment', new_forum_topic_comment_path(@topic.forum,@topic),{remote: true} %></p> </br>
<div id="comment_form"></div>
<h3>Listing Comments Of <%=@topic.subject%></h3>

<table class="table table-striped">
  <thead>
  <tr><th>Comments</th>
    
  </thead>
  <tbody id="comments_list">
<% @comments.each do |comment|%>
<tr id="comment_<%=comment.id%>">
<td><%=comment.body %>
Like Count: [<%= Like.get_like_count(comment.class,comment.id) %>]
      <%= link_to "like it!!", like_path(:resource_name => comment.class,
                                         :resource_id   => comment.id),
                                         :method => :post %>
     <%= link_to "unlike it!!", unlike_path(
                                        :resource_name => comment.class,
                                        :resource_id   => comment.id),
                                        :method => :delete %>



 </td>
<td><%=link_to 'Delete',forum_topic_comment_path(@topic.forum, @topic,comment),{method: :delete} %> </td>
<td>
<%= social_share_button_tag(comment.body, :url => (forum_topic_comment_url(@topic.forum, @topic,comment) +'#comment_'+comment.id.to_s )) %></td>
</tr>
<%end%>
</tbody>
</table>